// ソラリゼーション
var idCrvs = charIDToTypeID( "Crvs" );
    var desc44 = new ActionDescriptor();
    var idpresetKind = stringIDToTypeID( "presetKind" );
    var idpresetKindType = stringIDToTypeID( "presetKindType" );
    var idpresetKindCustom = stringIDToTypeID( "presetKindCustom" );
    desc44.putEnumerated( idpresetKind, idpresetKindType, idpresetKindCustom );
    var idAdjs = charIDToTypeID( "Adjs" );
        var list5 = new ActionList();
            var desc45 = new ActionDescriptor();
            var idChnl = charIDToTypeID( "Chnl" );
                var ref4 = new ActionReference();
                var idChnl = charIDToTypeID( "Chnl" );
                var idChnl = charIDToTypeID( "Chnl" );
                var idCmps = charIDToTypeID( "Cmps" );
                ref4.putEnumerated( idChnl, idChnl, idCmps );
            desc45.putReference( idChnl, ref4 );
            var idCrv = charIDToTypeID( "Crv " );
                var list6 = new ActionList();
                    var desc46 = new ActionDescriptor();
                    var idHrzn = charIDToTypeID( "Hrzn" );
                    desc46.putDouble( idHrzn, 0.000000 );
                    var idVrtc = charIDToTypeID( "Vrtc" );
                    desc46.putDouble( idVrtc, 0.000000 );
                var idPnt = charIDToTypeID( "Pnt " );
                list6.putObject( idPnt, desc46 );
                    var desc47 = new ActionDescriptor();
                    var idHrzn = charIDToTypeID( "Hrzn" );
                    desc47.putDouble( idHrzn, 73.000000 );
                    var idVrtc = charIDToTypeID( "Vrtc" );
                    desc47.putDouble( idVrtc, 204.000000 );
                var idPnt = charIDToTypeID( "Pnt " );
                list6.putObject( idPnt, desc47 );
                    var desc48 = new ActionDescriptor();
                    var idHrzn = charIDToTypeID( "Hrzn" );
                    desc48.putDouble( idHrzn, 127.000000 );
                    var idVrtc = charIDToTypeID( "Vrtc" );
                    desc48.putDouble( idVrtc, 129.000000 );
                var idPnt = charIDToTypeID( "Pnt " );
                list6.putObject( idPnt, desc48 );
                    var desc49 = new ActionDescriptor();
                    var idHrzn = charIDToTypeID( "Hrzn" );
                    desc49.putDouble( idHrzn, 181.000000 );
                    var idVrtc = charIDToTypeID( "Vrtc" );
                    desc49.putDouble( idVrtc, 41.000000 );
                var idPnt = charIDToTypeID( "Pnt " );
                list6.putObject( idPnt, desc49 );
                    var desc50 = new ActionDescriptor();
                    var idHrzn = charIDToTypeID( "Hrzn" );
                    desc50.putDouble( idHrzn, 255.000000 );
                    var idVrtc = charIDToTypeID( "Vrtc" );
                    desc50.putDouble( idVrtc, 255.000000 );
                var idPnt = charIDToTypeID( "Pnt " );
                list6.putObject( idPnt, desc50 );
            desc45.putList( idCrv, list6 );
        var idCrvA = charIDToTypeID( "CrvA" );
        list5.putObject( idCrvA, desc45 );
    desc44.putList( idAdjs, list5 );
executeAction( idCrvs, desc44, DialogModes.NO );